### ISSUE TITLE
MySql OperationalError

### ISSUE THREAD

**Issue by solarcloud7** [joinandplaycoop/Factorio-Scenarios#2]
![image](https://user-images.githubusercontent.com/758330/62431797-66866200-b6f0-11e9-9f22-bbb4bf83fb5e.png)

Solution for this:

`def sqlFunc(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except OperationalError as e:
            if 'MySQL server has gone away' in str(e):
                sql_operator.connect()
                return func(*args, **kwargs)
            print e
    return wrapper `

Link to example : [example](https://github.com/uin3566/Dota2Server/tree/master/spider/gl.py)

**Comment by IIPoliII** [comment]
Fail wrong project
