### ISSUE TITLE
Bunker scenario teleportation fixes

### ISSUE THREAD

**Issue by tuckert** [joinandplaycoop/Factorio-Scenarios#7]
Creating issue to help keep track.
In talking with RailOcelot in game, there are 2 issues with teleportation.  

1.  Setting spawn point removes the ability to go back into your bunker.
Cause: Teleportation is set to go back to spawn point.  
Fix:  Bunker location could be saved in player table.

2. Cannot enter someone else's bunker.
Cause: Same as up top.
Fix: Same as well.
This may not be issue.  The idea of personal bunkers supports the way it is now.  Perhaps an extra setting in the spawn ctrl panel can be added.

**Comment by IIPoliII** [comment]
The second idea is a good idea I never saw that issue, will check if I find anything I will ping you in case I find something.

**Comment by IIPoliII** [comment]
I think this has been fixed by tuckert. Reopen if it's not the case good work.
